demo:
  config:
    enable: true
    ids:
      - 1
      - 3
      - 4
    user-list:
      - id:
          5
        name:
          "张三"
        age:
          12
      - id:
          6
        name:
          "李四"
        age:
          18
    string-map:
      "[/key1]":
        "value1"
      "/key2":
        "value2"
      "key3":
        "value3"
      "a.b":
        "c"
      "[d.e]":
        "f"
    user-map:
      "key1.id":
        12
      "key1.name":
        "ssss"
      "key1.age":
        14
    num: 12

    app-id: demo-starter-sample
#    env: pro
#spring:
#  config:
#    import: classpath:/config/c1/c1[.yml]
