spring:
  config:
    import: classpath:/config/c1/c1.yml,classpath:/config/custom.yml

  rsocket:
    server:
      port: 7000

logging:
  level:
    web: debug

server:
  port: 8443
  ssl:
    key-store: classpath:winter.keystore
    key-store-password: 123456789
    key-password: 123456789

http:
  port: 8080

